### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by suprohub** [W1lliam1337/cstrike2-hack#1]
not working after inject

**Comment by W1lliam1337** [comment]
Can you provide more details?

**Comment by suprohub** [comment]
1 build release
2 inject via process hacker
3 press insert and not see window of cheat

**Comment by MaYecha** [comment]
Initializing core components...
Initialized module: client.dll 0x7ff86e0d0000
Initialized module: engine2.dll 0x7ff88ced0000
Initialized module: gameoverlayrenderer64.dll 0x7ff88dc70000
Init failed: could not find window

**Comment by jocko1337** [comment]
Error while injecting via process hacker, not sure what to do.
![Screenshot_9](https://github.com/user-attachments/assets/057ce236-0ece-4c97-853d-2edb08bf5a37)

**Comment by INKCR0W** [comment]
> Error while injecting via process hacker, not sure what to do. ![Screenshot_9](https://private-user-images.githubusercontent.com/176526826/351840942-057ce236-0ece-4c97-853d-2edb08bf5a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTA3MDYsIm5iZiI6MTcyMTg5MDQwNiwicGF0aCI6Ii8xNzY1MjY4MjYvMzUxODQwOTQyLTA1N2NlMjM2LTBlY2UtNGM5Ny04NTNkLTJlZGIwOGJmNWEzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNjUzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmZkY2M5NzNiZTg5YzA5YTc2N2M1OWNmMDM5NmE5ZTM1MWZkNmU3MjM2OTQyNTZlMjE0NmM3OTM5NGRkOGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qcdwdXbbUw1mQGBKmR2dRF1K-5iwqxQpfyPkAwju7qM)

You gotta inject it using manual mapping

**Comment by INKCR0W** [comment]
> Initializing core components... Initialized module: client.dll 0x7ff86e0d0000 Initialized module: engine2.dll 0x7ff88ced0000 Initialized module: gameoverlayrenderer64.dll 0x7ff88dc70000 Init failed: could not find window

You can check this [PR](https://github.com/W1lliam1337/cstrike2-hack/pull/3) (#3), I fixed it

**Comment by MaYecha** [comment]
> > Initializing core components... Initialized module: client.dll 0x7ff86e0d0000 Initialized module: engine2.dll 0x7ff88ced0000 Initialized module: gameoverlayrenderer64.dll 0x7ff88dc70000 Init failed: could not find window
> 
> You can check this [PR](https://github.com/W1lliam1337/cstrike2-hack/pull/3) (#3), I fixed it

injected,but esp not work

**Comment by MaYecha** [comment]
![image](https://github.com/user-attachments/assets/ff00b199-c9e3-48c9-a463-2014a5d4717a)

**Comment by MaYecha** [comment]
![image](https://github.com/user-attachments/assets/08be41a7-14b3-4fa1-b82d-95a61748ec81)

**Comment by INKCR0W** [comment]
> > > Initializing core components... Initialized module: client.dll 0x7ff86e0d0000 Initialized module: engine2.dll 0x7ff88ced0000 Initialized module: gameoverlayrenderer64.dll 0x7ff88dc70000 Init failed: could not find window
> > 
> > 
> > You can check this [PR](https://github.com/W1lliam1337/cstrike2-hack/pull/3) (#3), I fixed it
> 
> injected,but esp not work

this is just a framework, no features are currently implemented

**Comment by suprohub** [comment]
not works
